Bugfix: the exception ENOTFOUND crashed NodeJS
If a URL is invalid, an exception will be thrown and it can not be caught:

events.js:182
      throw er; // Unhandled 'error' event
      ^
Error: getaddrinfo ENOTFOUND www.domain.com www.domain.com:80
    at errnoException (dns.js:53:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:95:26)
	
Also, reject does not stop processing: if req is null, req.end() will throw an exception.
Can you publish a new version on NPM please?